### PR TITLE
[Release] 3.17.0

### PR DESCRIPTION
**Pull request by ryan-conway**
https://github.com/nimblehq/android-templates/milestone/20

## Features
- #159 
- #354

## Chores
- #297 
- #379

## Bugs
- #394 
- #405

### CODE REVIEW

**Review by thiennguyen0196 — APPROVED** [review]

**Comment by luongvo** [comment]
@ryan-conway Should we wait for the Part 3 https://github.com/nimblehq/android-templates/pull/416 to complete the whole task for the release? cc @lydiasama

**Comment by ryan-conway** [comment]
@luongvo According to the [repository maintainers handbook](https://www.notion.so/nimblehq/Repository-Maintainer-Handbook-35e3671666d740429f212e7e9fbacbbd) that @Tuubz created, releases should happen at the end of the cycle, meaning this release is already late as it should have been made on Feb 28. But if #416 does get merged today, I don't see why we shouldn't include it in this release 🙏🏻

**Comment by lydiasama** [comment]
@luongvo @ryan-conway I'm on it now. 🙏🏻

**Review by AVI5HEK — APPROVED** [review]

**Review by lydiasama — APPROVED** [review]

**Review by luongvo — APPROVED** [review]
~@ryan-conway please list #159 in the release note.~

**Review by doannimble — APPROVED** [review]

**Pull request merged**
