### PR TITLE
[#179] Fix: incorrect Jacoco coverage report after migrating to Kotlin DSL

### PR DESCRIPTION
**Pull request by luongvo**
https://github.com/nimblehq/android-templates/issues/179

## What happened 👀

After migrating [Jacoco config to Kotlin DSL](https://github.com/nimblehq/android-templates/pull/145), Jacoco is reporting **incorrect** coverage with some redundant packages and classes.

## Insight 📝

- In Kotlin DSL, we need to add `**/` prefix for package excludes.
- There are also some more packages and classes that should be excluded, such as Hilt, Nav Component, Data binding, Kotlin enum, etc.

```
dagger.hilt.internal.aggregatedroot.codegen
dagger.hilt.internal.processedrootsentinel.codegen
hilt_aggregated_deps
```

## Proof Of Work 📹

|  After | Before |
| - | - |
| image | image | 
| image | image | 
| image | image | 
| image | image | 
| image | image | 
| image | image |

### CODE REVIEW

**Comment by Tuubz** [comment]
@luongvo Is it possible for us to exclude these as well? 💭 

Screen Shot 2565-04-05 at 10 12 02

**Comment by luongvo** [comment]
> @luongvo Is it possible for us to exclude these as well? 💭
> 
> Screen Shot 2565-04-05 at 10 12 02

@Tuubz Actually, they are our written code, it's just the way that Jacoco tries to show code coverage for Kotlin Lamba funcs. I don't see a good reason to remove it. 🤔

**Comment by Tuubz** [comment]
> > @luongvo Is it possible for us to exclude these as well? 💭
> > Screen Shot 2565-04-05 at 10 12 02
> 
> @Tuubz Actually, they are our written code, it's just the way that Jacoco tries to show code coverage for Kotlin Lamba funcs. I don't see a good reason to remove it. 🤔

I could be wrong, but the ones that I highlighted in the screenshot are reflected already in `HomeFragment.kt`. 

So it feels a bit redundant, what do you think?

**Comment by luongvo** [comment]
> > > @luongvo Is it possible for us to exclude these as well? 💭
> > > Screen Shot 2565-04-05 at 10 12 02
> > 
> > 
> > @Tuubz Actually, they are our written code, it's just the way that Jacoco tries to show code coverage for Kotlin Lamba funcs. I don't see a good reason to remove it. 🤔
> 
> I could be wrong, but the ones that I highlighted in the screenshot are reflected already in `HomeFragment.kt`.
> 
> So it feels a bit redundant, what do you think?

@Tuubz I see, but because lambda funcs are parts of Kotlin language so we can't exclude lambda function out of the coverage report. That's the support of Jacoco for Kotlin lang, not an issue I think. You can check out more at https://www.jacoco.org/jacoco/trunk/doc/changes.html

**Review by Tuubz — APPROVED** [review]
@luongvo I still have a strong urge to remove them from the report (especially because some of them show `Source file "xxx.kt" was not found during generation of report.` once you click on them.)

Example:
Screen Shot 2565-04-05 at 11 01 41

Anyways, your code changes are definitely an improvement from before, so approved 🚀

Maybe it's something we can look in to again later

**Comment by luongvo** [comment]
@Tuubz Thank you, I tried to focus on excluding generated files that affect our coverage statistics rather than excluding some coverage detail that does not affect the coverage of container files. 🤓 

For example:
- DI and Hilt generated files > no need to test, should be excluded to increase the main coverage of our actual written code.
- Lamba and inline functions > need to be tested, should not be excluded from the main coverage (except we can find a way to hide it without changing coverage statistics).

**Review by Wadeewee — APPROVED** [review]

**Comment by Tuubz** [comment]
@nimblehq/android-chapter Could we get one more approval here, please? 🤩

**Review by doannimble — APPROVED** [review]

**Pull request merged**
