### PR TITLE
[Chore] Update reviewer list

### PR DESCRIPTION
**Pull request by Tuubz**
## What happened 👀

@thiennguyen0196 a.k.a Bruce was missing from the list  👋 

## Insight 📝

N/A

## Proof Of Work 📹

N/A

### CODE REVIEW

**Review by chornerman — APPROVED** [review]
LGTM 🚀

**Review by AVI5HEK — APPROVED** [review]

**Review by doannimble — APPROVED** [review]
LGTM

**Review by minhnimble — APPROVED** [review]
LGTM 🚀

**Comment by Tuubz** [comment]
Strange...

The code owner icon is missing now, except for engineering leads 🤔 

Screenshot 2022-11-03 at 11 40 09

**Review by lydiasama — APPROVED** [review]

**Pull request merged**
