### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by lydiasama**
## What happened 👀

Release 3.1.0 to main

### CODE REVIEW

**Comment by hoangnguyen92dn** [comment]
@lydiasama After confirmed on the Slack channel, we could close this PR, right?

**Comment by luongvo** [comment]
I think we should change the title of this PR to be a release PR, such as `Release 3.1.0` because there was a 3.0.0 release here #104, ...and this PR will be in Draft quite long 🤓

**Comment by hoangnguyen92dn** [comment]
@lydiasama I thought we should have released last Friday? 🤔

**Comment by lydiasama** [comment]
@hoangnguyen92dn I'm waiting for [the last PR](https://github.com/nimblehq/android-templates/pull/103). Sorry for that. 🙇🏻‍♀️

**Review by luongvo — APPROVED** [review]

**Review by chornerman — APPROVED** [review]

**Pull request merged**
