### PR TITLE
[#454] Update generating project example script to be in Fenced Code Block

### PR DESCRIPTION
**Pull request by lydiasama**
- Closes https://github.com/nimblehq/android-templates/issues/454

## What happened 👀

Update code block script from double backticks code (``) to the [Fenced Code Block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)

## Insight 📝

N/A

## Proof Of Work 📹

Screenshot 2566-07-06 at 11 10 22 AM

### CODE REVIEW

**Review by sleepylee — APPROVED** [review]

**Review by doannimble — APPROVED** [review]

**Review by luongvo — APPROVED** [review]

**Review by AVI5HEK — APPROVED** [review]

**Comment by lydiasama** [comment]
Screenshot 2566-07-06 at 11 29 44 AM

Can we ignore this error? 😢

**Comment by luongvo** [comment]
> Screenshot 2566-07-06 at 11 29 44 AM
> 
> Can we ignore this error? 😢

@lydiasama @ryan-conway I think we should create a task to switch to [using Chucker from Maven Central](https://github.com/ChuckerTeam/chucker#getting-started-) instead of Jitpack. Jitpack server is not stable sometimes, so use it only if there is no other way 🤓 

FYI: I faced the same issue in the Gulf project but forget to raise a ticket.

**Comment by lydiasama** [comment]
@luongvo Haven't we set it from the maven? 🤔 

Screenshot 2566-07-06 at 11 39 28 AM

**Comment by luongvo** [comment]
> @luongvo Haven't we set it from the maven? 🤔
> 
> Screenshot 2566-07-06 at 11 39 28 AM

@lydiasama maybe, we MUST move up the mavenCentral config here. That needs time for investigation 🤷‍♂️ 

image

**Review by chornerman — APPROVED** [review]

**Comment by lydiasama** [comment]
@ryan-conway Since the CI error is related to Chunker dependency, shall we merge this PR first and then create another issue to resolve it? 🙏🏻

**Review by kaungkhantsoe — APPROVED** [review]

**Comment by lydiasama** [comment]
> > @luongvo Haven't we set it from the maven? 🤔
> > Screenshot 2566-07-06 at 11 39 28 AM
> 
> @lydiasama maybe, we MUST move up the mavenCentral config here as both use the same dependency id. That needs time for investigation 🤷‍♂️
> 
> image

@luongvo I found the root cause. It's not related to Jitpack connection, instead, it's about the syntax we implemented. With [this solution](https://stackoverflow.com/a/66926254/11393626), It's resolved it https://github.com/nimblehq/android-templates/pull/484 🤓

**Pull request merged**
