### PR TITLE
[Release] 3.1.0

### PR DESCRIPTION
**Pull request by lydiasama**
https://github.com/nimblehq/android-templates/milestone/4

Since we have done Release `3.1.0` before, but we need to keep release once a month, so I intend to keep the same release version as `3.1.0` for this release.

### Features

- #86 
- #87 
- #98 

### Chores

- #95 
- #105 

-------------------------------------------------------------

### Features

N/A

### Chores

- #112 
- #117 
- #122 

### Bugs

N/A

### CODE REVIEW

**Comment by luongvo** [comment]
@lydiasama I don't see enough PR merge points in the commit list, do we really have all of them in this release? 🤔

**Comment by lydiasama** [comment]
@luongvo We do the release 3.1.0 once before this. In this description, since we have the release template, I intend to include all of the 3.1.0 changes. 🙏🏻

**Comment by luongvo** [comment]
> @luongvo We do the release 3.1.0 once before this. In this description, since we have the release template, I intend to include all of the 3.1.0 changes. 🙏🏻

So better to have a reference to the last release, I guess it's #109

**Comment by lydiasama** [comment]
@luongvo @Tuubz Updated.

**Review by Tuubz — APPROVED** [review]

**Review by chornerman — APPROVED** [review]

**Review by minhnimble — APPROVED** [review]

**Pull request merged**
