### PR TITLE
Add the Github release PR template

### LINKED ISSUE #112: Create a Github template for the release PRs
## Why

We already have the [pull request template](https://github.com/nimblehq/android-templates/blob/main/.github/PULL_REQUEST_TEMPLATE.md) in the Android template. But that template isn't applicable for the releases. As a result, the release PRs format can be inconsistent between every project. 
As we now have the [convention](https://nimblehq.co/compass/development/version-control/release-management/#release-pull-request) for the release PR, it should be reflected in this template.

## Who Benefits?

Android chapter

### PR DESCRIPTION
**Pull request by longnd**
Resolves #112 

## What happened 👀

As part of the engineering initiatives, this PR adds the Github template for the release pull requests that match Nimble's [convention](https://nimblehq.co/compass/development/version-control/release-management/#release-pull-request).
 
## Insight 📝

The implementation is identical with https://github.com/nimblehq/git-template/pull/15. 
Github supports multiple [templates for issues and pull requests](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). For example, to define multiple pull request templates, simply define them like this:
```bash
.github
└── PULL_REQUEST_TEMPLATE
    ├── normal_template.md
    └── release_template.md
```

But unlike issue templates - when opening a new issue, Github will show a template selection menu:
Screen Shot 2021-06-24 at 09 24 41

even with multiple pull request templates defined, a UI to select the template isn't available yet. It is a known issue (read more: [(1)](https://github.community/t/multiple-pull-request-templates/1850), [(2)](https://github.community/t/multiple-pull-request-template/874)). 
As a result, when opening a new pull request, we have to specify the template manually by putting a query param `?template=<template_name.md>` into the pull request URL, e.g. 

`https://github.com/nimblehq/git-template/compare/chore/add-release-pull-request-template?expand=1&`**template=release_template.md**

Also, Github doesn't support setting a default template for new pull requests if putting all templates under `PULL_REQUEST_TEMPLATE` directory

So I ended up organizing the templates like this:
```bash
.github
├── PULL_REQUEST_TEMPLATE
│   └── RELEASE_TEMPLATE.md
└── PULL_REQUEST_TEMPLATE.md
```
with the above structure, when opening a new pull request, without the `?template` param provided, Github still uses the default template defined by `PULL_REQUEST_TEMPLATE.md`. And when we need to use a new template, in this case, the release template, we must specify it in the URL.

 
## Proof Of Work 📹

I created a test repo. When opening a [new pull request](https://github.com/longnd/awesomedemo/compare/main...chore/template) without the `template` param specified, the default template is used:

Screen Shot 2021-06-24 at 09 36 13

And when specify the template, that template is used:

Screen Shot 2021-06-24 at 09 38 53

### CODE REVIEW

**Comment by longnd** [comment]
I don't have write access in this repository so I forked it to be able to submit this PR. That's why I can't add the PR's attributes (assignee, label, ...) 🙈

**Comment by luongvo** [comment]
> I don't have write access in this repository so I forked it to be able to submit this PR. That's why I can't add the PR's attributes (assignee, label, ...) 🙈

@longnd I'm wondering is there any documented step to create a new release PR from a release template? Not sure if everyone knows the way to put the template param `` at the end of the link when creating a new PR 🤔 

`https://github.com/nimblehq/git-template/compare/chore/add-release-pull-request-template?template=release_template.md`

image

**Comment by longnd** [comment]
> @longnd I'm wondering is there any documented step to create a new release PR from a release template? Not sure if everyone knows the way to put the template param at the end of the link when creating a new PR 🤔
> 
> `https://github.com/nimblehq/git-template/compare/chore/add-release-pull-request-template?template=release_template.md`
> 
That's a valid concern. How about adding a `.github/REAME.md` file with instructions @luongvo ?

**Comment by luongvo** [comment]
> That's a valid concern. How about adding a `.github/README.md` file with instruction @luongvo ?

@longnd how about adding instruction in README, and also mention it in the default template too. I doubt sometimes someone does not remember to create a release PR correctly.

**Comment by longnd** [comment]
> > That's a valid concern. How about adding a `.github/README.md` file with instruction @luongvo ?
> 
> how about adding instruction in README, and also mention it in the default template too. I doubt sometimes someone does not remember to create a release PR correctly.

@luongvo I added a note into the default template in bc951a3. Creating an additional `.github/README.md` isn't suitable in this case because it will override the repository' root `README.md` file when rendering on the repository home page.

**Comment by luongvo** [comment]
> > > That's a valid concern. How about adding a `.github/README.md` file with instruction @luongvo ?
> > 
> > 
> > how about adding instruction in README, and also mention it in the default template too. I doubt sometimes someone does not remember to create a release PR correctly.
> 
> @luongvo I added a note into the default template in [bc951a3](https://github.com/nimblehq/android-templates/commit/bc951a3113b76f71e7b9d2b4c92540340e161d65). Creating an additional `.github/README.md` isn't suitable in this case because it will override the repository' root `README.md` file when rendering on the repository home page.

@longnd Sorry but where did you add this commit [bc951a3](https://github.com/nimblehq/android-templates/commit/bc951a3113b76f71e7b9d2b4c92540340e161d65)? I can't see it in this PR, or you pushed it up somewhere? 🤔

**Review by minhnimble — APPROVED** [review]

**Review by AVI5HEK — APPROVED** [review]

**Review by lydiasama — APPROVED** [review]

**Pull request merged**
