### PR TITLE
[View Binding] Migrate CoroutineTemplate UIs to view binding

### PR DESCRIPTION
**Pull request by manh-t**
https://github.com/nimblehq/android-templates/projects/3#card-52783420

## What happened 🤔

Migrate RxJavaTemplate UIs to View Binding

## PoW (a.k.a Proof Of Work)💪

App works normally

https://user-images.githubusercontent.com/60863885/119430534-29fb7e80-bd3b-11eb-8738-67966a1dc6e2.mp4

### CODE REVIEW

**Review by luongvo — APPROVED** [review]
lgtm

**Review by minhnimble — APPROVED** [review]
LGTM 🚀

**Comment by hoangnguyen92dn** [comment]
@manh-t Will we setup base test classes in the next PR?

**Comment by manh-t** [comment]
> @manh-t Will we setup base test classes in the next PR?

Yes 👍

**Review by hoangnguyen92dn — APPROVED** [review]

**Pull request merged**
